### ISSUE TITLE
Question regarding the state of this project

### ISSUE THREAD

**Issue by MMachado05** [joseantmazonsb/linguard#121]
It seems like the last commit to either branch (dev or main) was 3 years ago; is this project still being worked on? It seems like an incredibly useful utility, but using network-related software 3 years out of date feels like poor security practice.

**Comment by joseantmazonsb** [comment]
Hi there, i've been working on a new React + Express version for a while now, with some improvements and new features, but it's nowhere near production-ready yet. It's been a couple very busy years for me, but things have started to calm down now and I'd really like to dedicate more time to this project. I'll probably start by publishing this new version in a new branch and see how things go

**Comment by MMachado05** [comment]
That's super awesome to hear! Obviously take your time, I'm confident that developing an open-source tool is tough work, especially when it can't be monetized. I just wanted to know if the codebase had been migrated or something similar. I'm excited to see what you'll be able to do! 😁
