### ISSUE TITLE
Add TLS.

### ISSUE THREAD

**Issue by joseantmazonsb** [joseantmazonsb/linguard#14]
The user will be able to edit the uwsgi TLS settings via Linguard's UX.

**Comment by joseantmazonsb** [comment]
Blocked by #12

**Comment by joseantmazonsb** [comment]
I think maybe it has more sense to just provide the instructions to reverse proxy the application...

**Comment by Some1OnLine** [comment]
> I think maybe it has more sense to just provide the instructions to reverse proxy the application...

This would be great as I currently reverse proxy via Apache2 a lot of web urls I host.

**Comment by joseantmazonsb** [comment]
> > I think maybe it has more sense to just provide the instructions to reverse proxy the application...
> 
> This would be great as I currently reverse proxy via Apache2 a lot of web urls I host.

I could add a template for Apache and Nginx in the readme
