### ISSUE TITLE
limit user traffic

### ISSUE THREAD

**Issue by AnonymousWebHacker** [joseantmazonsb/linguard#93]
Linguard is great, it just lacks a way to control the total traffic of the connecting user. In my case I do not want to exceed the traffic of my vps

**Comment by joseantmazonsb** [comment]
Hi there! I'm sorry but Linguard is just a web interface to manage a Wireguard server, and hence this would be out of scope. However, you can specify quotas using `iptables` rules when the interface is brought up via `on_up` rules (directly from the Linguard UX) or manually.

**Comment by AnonymousWebHacker** [comment]
It would be good if you added those options in Linguard
