### ISSUE TITLE
Not showing correctly in Nginx reverse proxy subdirectory 

### ISSUE THREAD

**Issue by kimiroo** [joseantmazonsb/linguard#94]
Linguard not showing correctly when configured to be served via nginx subdir reverse proxy.

Used configuration:

```
location /linguard/ {
#    rewrite ^/linguard/(.*) /$1  break;
    proxy_pass http://127.0.0.1:8080;
#    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
```

adding rewrite rule doesn't help.

**Comment by jine** [comment]
We're running linguard behind a Nginx Proxy aswell, without any issues - what seems to be wrong? 

Can you provide more details of whats happening and whats not working/showing correctly? I'm guessing it's related to the path's you're using - if you're using a path such as /linguard as the endpath - the hardcoded URLs in the app won't work (as they're set to these below). A easy solution would be to keep using / as path, not /linguard....

<link href="/static/css/styles.css" rel="stylesheet" />
  
  and smilar won't work,

**Comment by kimiroo** [comment]
Ok. I guess there isn't way to solve this problem on my side. Creating feature request for support for reverse proxy in subdirectory..
